apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 2  # Number of workers
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: simransar/locust-load-tester:latest
          args: ["--worker", "--master-host=locust-master", "--master-port=5557"]  # Ensure this matches your master service name
          resources:                             # Define resource requests and limits
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
