apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: health-checker-rolebinding
  namespace: default  # Same namespace as the Role and ServiceAccount
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default  # Ensure this matches the namespace where the health checker is running
roleRef:
  kind: Role
  name: health-checker-role
  apiGroup: rbac.authorization.k8s.io
