apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: health-checker-role
  namespace: default  # Ensure this matches the namespace where the health checker runs
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "configmaps"]
    verbs: ["get", "list", "patch", "update", "create"]
